### ISSUE TITLE
Button for LNA

### ISSUE THREAD

**Issue by vsboost** [jocover/ExtIO_HackRF#1]
Thanks for making this, just a feature request for an LNA button.

**Comment by timhavens** [comment]
Thank you also for making this!  Works GREAT!

I wonder if you could add more options to the MSPS (sample rate) to get down to 4 and 2 ?

I use HDSDR for weak signal work, and although I WILL use 8-20 msps from time to time, I would like the option to use less.

If you don't want to add that option I can just make the change myself, and compile it locally.  SO no problem.

BUT KUDOS!  Thank you so much for making this!  Works GREAT.

**Comment by vsboost** [comment]
Thanks for the RF gain slider, earlier when i mentioned a button for the LNA i meant the RF amp within the hackrf if possible, just to enable or disable.

The three RX gain controls are at the 
RF ("amp", 0 or 14 dB), 
IF ("lna", 0 to 40 dB in 8 dB steps), and 
Baseband ("vga", 0 to 62 dB in 2 dB steps) stages

**Comment by timhavens** [comment]
jcover: Thank you for the 2 & 4 msps options!  Also the fast response this is perfect!  Very impressive.

**Comment by jocover** [comment]
add AMP button support

**Comment by vsboost** [comment]
Thanks for the amp button..
