### ISSUE TITLE
TX support

### ISSUE THREAD

**Issue by vsboost** [jocover/ExtIO_HackRF#2]
In v0.03 i could select TX support, but i could not get it to TX, in v0.04 TX support is not allowed.

HDSDR Error:
Actual ExtIO DLL does not support TX!

**Comment by jocover** [comment]
thanks ,i forget to open the feature

**Comment by vsboost** [comment]
Thank you

**Comment by vsboost** [comment]
Closed this as it requires further coding from the author of HDSDR.
