### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Jabieraru** [jocover/ExtIO_HackRF#3]
I have downloaded the last version and not is running on the HPSDR. Any solution? Running on Windows 7 Ultimate.

**Comment by vsboost** [comment]
I am running on both Win 8.1 x64 and Win 7 x64 and have no problems.

**Comment by jocover** [comment]
you need this :http://www.microsoft.com/en-us/download/details.aspx?id=40784
or download dll version ExtIO_HackRF
https://github.com/jocover/ExtIO_HackRF/releases/download/0.06/ExtIO_HackRF_DLL.zip
