### ISSUE TITLE
Please add .5 msps and 1 msps

### ISSUE THREAD

**Issue by timhavens** [jocover/ExtIO_HackRF#4]
Hello, I was the requester of the 2 and 4 msps addition you made recently.

In HDSDR the "RBW" at 2 msps minimum is 7.6hz.  Which is pretty good for the weak signal stuff I do.

However, it was such and improvement over 8 msps and it's min. of 30.5hz that I would like  to try to see how small the min RBW would be if the msps was .5 or 1.  

Could you please consider added these to the sample rate drop down for me?

--------

BTW I'm a software developer as well, but 95% of what I do is on Linux.  I tried to get the source to compile in VS 2012 but can't seem to get the HackRF headers linked in properly :-(

Any hints for that?  I hate to pester for things like what I'm asking for above if I could just compile this myself for my own needs.

**Comment by jocover** [comment]
https://www.dropbox.com/s/0asrmowb5ehdxw2/ExtIO_HackRF.dll?dl=0

**Comment by timhavens** [comment]
Thank you this gets RBW to 3.8 Hz now...will try this for a while.  Looks ok.
