### ISSUE TITLE
Issue with using HackRF with Omni-Rig Cat Control

### ISSUE THREAD

**Issue by fang64** [jocover/ExtIO_HackRF#7]
Hello, 

I have a Kenwood TS-480 radio controlled over Omni-Rig interface, and when I change mode via the GUI it throws the error below. When I change the mode at the radio via Omni-Rig sync'ing it doesn't seem to have an issue with the change. I can follow up with some debugging if it needs to happen.

![hdsdr-error](https://cloud.githubusercontent.com/assets/649502/10123256/1c4e9290-6503-11e5-989d-8a354d99db14.png)

**Comment by jocover** [comment]
thanks , the newest version fixed the bug

**Comment by fang64** [comment]
@jocover I'll give a test when I get a chance. Thanks!
