### ISSUE TITLE
Windows 10 ?

### ISSUE THREAD

**Issue by timhavens** [jocover/ExtIO_HackRF#8]
I just installed windows 10 pro.  I've been using the HackRF_Extio.DLL for a while now with HDSDR with no problems on Windows 7 pro.  However, Windows 10 pro doesn't seem to be finding it.  Could be something wrong here, but no hardware changes have been made, all the same exact connections exist.

I just wonder if I've forgotten some step to make this work, or if there is something that needs to be added to make it work in Windows 10?

Tim

**Comment by jocover** [comment]
work fine on win10

**Comment by timhavens** [comment]
ok thank you.

On Mon, Oct 5, 2015 at 3:46 AM, jocover <notifications@github.com> wrote:

> work fine on win10
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jocover/ExtIO_HackRF/issues/8#issuecomment-145422834>.
>



-- 
“Real knowledge is to know the extent of one’s ignorance.”  ~Confucius (551
BC - 479 BC)

Tim R. Havens
Google Phone: 573.454.1232
Skype: timhavens
ICBM:  37°51'34.79"N   90°35'24.35"W
ham radio callsign: NW0W
